<?php defined('C5_EXECUTE') or die(_("Access Denied."));
$session = \Core::make('session');
$themeColors = $session->get('anitya.colors');
print_r($themeColors);
$v =  $themeColors->variables;

?>
/*
** Let's start with some override from dashboard option's page
** This file is generated by php and placed into theme_anitya / elements / overrides.css.php
** Page name : <?php echo $c->getCollectionName() ?> / Theme preset Name : <?php echo $option_object->get_preset_title($o->pID) ?> / Theme preset ID : <?php echo $o->pID ?>

*/

/* --- Text Overrides --- */

<?php
$p 	= new \Concrete\Package\ThemeAnitya\Src\Models\MclFont('p');
$alternate 	= new \Concrete\Package\ThemeAnitya\Src\Models\MclFont('alternate');
$h1 = new \Concrete\Package\ThemeAnitya\Src\Models\MclFont('h1');
$h2 = new \Concrete\Package\ThemeAnitya\Src\Models\MclFont('h2');
$h3 = new \Concrete\Package\ThemeAnitya\Src\Models\MclFont('h3');
$h4 = new \Concrete\Package\ThemeAnitya\Src\Models\MclFont('h4');
$h5 = new \Concrete\Package\ThemeAnitya\Src\Models\MclFont('h5');
$h6 = new \Concrete\Package\ThemeAnitya\Src\Models\MclFont('h6');
$small = new \Concrete\Package\ThemeAnitya\Src\Models\MclFont('small');
?>

/* -- FONTS --- */

.alternate, .tp-caption.big_alternate  {
	<?=$alternate->getStyleCss()?>
	font-size:<?php echo $o->alternate_size?>em;
}

body, p {
	<?=$p->getStyleCss()?>
}
h1,.h1 {<?=$h1->getStyleCss()?>;font-size:<?=$h1->fullsize?>px}
h2,.h2 {<?=$h2->getStyleCss()?>;font-size:<?=$h2->fullsize?>px}
h3,.h3 {<?=$h3->getStyleCss()?>;font-size:<?=$h3->fullsize?>px}
h4,.h4 {<?=$h4->getStyleCss()?>;font-size:<?=$h4->fullsize?>px}
h5,.h5 {<?=$h5->getStyleCss()?>;font-size:<?=$h5->fullsize?>px}
h6,.h6 {<?=$h6->getStyleCss()?>;font-size:<?=$h6->fullsize?>px}

/* -- Navigation -- */
<?php if ($o->header_nav_selected_bar_wheight): ?>
.regular-top-nav > ul > li.active > a,
.regular-top-nav > ul > li:hover > a {
	box-shadow: 0 -<?php echo $o->header_nav_selected_bar_wheight?>px 0 <?php echo $v['primary-color'] ?>;
}

.regular-top-nav > ul > li > a {
	margin-top: <?php echo $o->header_nav_selected_bar_wheight  ?>px;
	line-height: <?php echo $v['top-nav-height-size'] - ($o->header_nav_selected_bar_wheight * 2 ) ?>px;
	padding-bottom: <?php echo $o->header_nav_selected_bar_wheight ?>px;
}

<?php endif ?>

/* -- Popup -- */

/* content at start */
.mfp-effect.mfp-wrap .mfp-content {
	<?php echo $o->popup_content_start_css ?>
}
/* content animate it */
.mfp-effect.mfp-wrap.mfp-ready .mfp-content {
	<?php echo $o->popup_content_animate_css ?>
}
/* content animate out */
.mfp-effect.mfp-wrap.mfp-removing .mfp-content {
	<?php echo $o->popup_content_out_css ?>
}

/* --- Large desktop */
@media (min-width: 1200px) {

	/* a {font-size:<?=$p->widesize?>px} */
	h1 {font-size:<?=$h1->widesize?>px}
	h2 {font-size:<?=$h2->widesize?>px}
	h3 {font-size:<?=$h3->widesize?>px}
	h4 {font-size:<?=$h4->widesize?>px}
	h5 {font-size:<?=$h5->widesize?>px}
	h6 {font-size:<?=$h6->widesize?>px}

}

/* --- Portrait tablet to landscape and desktop */
@media (min-width: 768px) and (max-width: 979px) {

	body {font-size:<?=$p->tabletsize?>px}
	/* a {font-size:<?=$p->tabletsize?>px} */
	h1 {font-size:<?=$h1->tabletsize?>px}
	h2 {font-size:<?=$h2->tabletsize?>px}
	h3 {font-size:<?=$h3->tabletsize?>px}
	h4 {font-size:<?=$h4->tabletsize?>px}
	h5 {font-size:<?=$h5->tabletsize?>px}
	h6 {font-size:<?=$h6->tabletsize?>px}

}

/* --- Landscape phone to portrait tablet */
@media (max-width: 767px) {
	p,li {font-size:<?=$p->fullsize?>px}
	h1 {font-size:<?=$h1->fullsize?>px}
	h2 {font-size:<?=$h2->fullsize?>px}
	h3 {font-size:<?=$h3->fullsize?>px}
	h4 {font-size:<?=$h4->fullsize?>px}
	h5 {font-size:<?=$h5->fullsize?>px}
	h6 {font-size:<?=$h6->fullsize?>px}
}

/* --- Landscape phones and down */
@media (max-width: 480px) {

}
